
[[language]]
name = "rust"
scope = "source.rust"
auto-format = true

[[language]]
name = "c"
scope = "source.c"
auto-format = true

[[language]]
name = "cpp"
scope = "source.cpp"
auto-format = true

[[language]]
name = "python"
scope = "source.python"
auto-format = true

[[language]]
name = "toml"
scope = "source.toml"
auto-format = true
