#!/bin/sh

case "$(grep -oP 'Layout = "\K[^"]+' ~/.config/hypr/modules/variables.lua)" in
    Scrolling)
        next="Dwindle"
        ;;
    Dwindle)
        next="Master"
        ;;
    Master)
        next="Monocle"
        ;;
    Monocle)
        next="Scrolling"
        ;;
esac

sed -i "s/Layout = \"[^\"]*\"/Layout = \"$next\"/" \
    ~/.config/hypr/modules/variables.lua

hyprctl reload
